name: Deploy image to server

on:
  workflow_dispatch:
    inputs:
      IMAGE:
        description: Image with tag
        default: "docker.io/library/alpine:3.11"
        required: true
      CONTAINER:
        description: Container name
        default: alp
        required: true

env:
  HOST: "your-app.com:3000/deploy/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send deploy request
        uses: wei/curl@v1
        with:
          args: |
            -f -v -X POST ${{ env.HOST }} \
            -H 'Authorization: ${{ secrets.DEPLOYER_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{\"name\":\"${{ github.event.inputs.CONTAINER }}\",\"image\":\"${{ github.event.inputs.IMAGE }}\",\"token\":\"${{ secrets.DOCKER_TOKEN }}\",\"user\":\"${{ secrets.DOCKER_USER }}\",\"network\":\"network-name\",\"tty\":true,\"env\":{\"ENV_VAR\":\"${{ secrets.ENV_VAR_VALUE }}\",\"ENV_VAR_2\":\"ENV_VAR2_VALUE\"},\"volumes\":[{\"source\":\"/home/centos/src\",\"target\":\"/var/www\"}]}'